name: screen_brightness_platform_interface
description: A common platform interface for the screen_brightness plugin
version: 0.1.0
homepage: https://github.com/aaassseee/screen_brightness
repository: https://github.com/aaassseee/screen_brightness/tree/master/screen_brightness_platform_interface
issue_tracker: https://github.com/aaassseee/screen_brightness/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4